apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  selector:
    matchLabels:
      app: student-app
  replicas: 3
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: student-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom :
                configMapKeyRef :
                  name: db-config
                  key : host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "nc -z postgres 5432"
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: NodePort
